# Generated by Django 4.0.1 on 2022-01-25 07:36

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(validators=[myapp.models.Coupon.start_date]),
        ),
    ]
